// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: job.proto
// </auto-generated>

extern alias extensions;

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace AICore
{

    [global::ProtoBuf.ProtoContract()]
    public partial class JobRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"job_id")]
        public uint JobId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"job_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string JobType { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? Time { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"payload")]
        public byte[] Payload { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JobResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"job_id")]
        public uint JobId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"job_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string JobType { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"duration")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.TimeSpan? Duration { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"payload")]
        public byte[] Payload { get; set; }

    }

    [global::ProtoBuf.Grpc.Configuration.Service(@"job.JobManager")]
    public partial interface IJobManager
    {
        extensions::System.Threading.Tasks.ValueTask<JobResponse> JobServiceAsync(JobRequest value, global::ProtoBuf.Grpc.CallContext context = default);
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
